---
- name: Validate role variables.
  ansible.builtin.import_tasks: assert.yml
  tags:
    - always

# Using encryption of data in transit with the Amazon EFS mount
# helper requires OpenSSL version 1.0.2 or newer.
- name: Install dependencies for Amazon EFS Utils.
  ansible.builtin.package:
    name:
      - gcc
      - openssl-devel
      - tcp_wrappers-devel
    state: present

# AWS EFS Utils requires a version of stunnel that
# supports both OCSP and certificate hostname checking.
# EL 7 comes with stunnel-4.56; OCSP was added in 4.16.
# Stunnel 5.15 from 2015 adds the checkHost openssl 1.0.2 support
# https://www.stunnel.org/sdf_ChangeLog.html
- name: Install newer Stunnel for RedHat from IUS.
  ansible.builtin.package:
    name: stunnel5u
    state: present
  when: ansible_os_family == "RedHat"

# This will fail if you don't already point at a repository which
# contains an amazon-efs-utils RPM in config before this role.
# It should succeed on Amazon linux.
- name: Install Amazon EFS Utils.
  ansible.builtin.package:
    name: amazon-efs-utils
    state: present

- name: Install nfs-common (Debian).
  ansible.builtin.package:
    name: nfs-common
    state: present
  when: ansible_os_family == 'Debian'

- name: Install nfs-utils (RedHat).
  ansible.builtin.package:
    name: nfs-utils
    state: present
  when: ansible_os_family == 'RedHat'

# mkdir -p ${efs_directory}
- name: Create directories for the mounts.
  ansible.builtin.file:
    path: "{{ item.path | default('/mnt/efs') }}"
    state: directory
    mode: "{{ item.mode | default('0644') }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
  loop: "{{ aws_efs_paths }}"

# echo "${file_system_id_01}:/ ${efs_directory} efs tls,_netdev" >> /etc/fstab
# mount -a -t efs defaults
- name: Mount paths.
  ansible.posix.mount:
    path: "{{ item.path | default('/mnt/efs') }}"
    src: "{{ item.filesystem_id }}:/"
    fstype: efs
    opts: "{{ item.defaults | default('tls') }},_netdev"
    state: mounted
  loop: "{{ aws_efs_paths }}"
